#ifndef _DC_RENDER_CONSTANTS_DEMOONE_
#define _DC_RENDER_CONSTANTS_DEMOONE_

#include "dcRender.h"

#define RENDER_WIDTH 320
#define RENDER_HEIGHT 240
#define RENDER_BG_COLOR_R 44
#define RENDER_BG_COLOR_G 54
#define RENDER_BG_COLOR_B 69
#define RENDER_ORDER_TABLE_SIZE 4096
#define RENDER_PRIMITIVES_LIST_SIZE 8192

#endif